# ASSIGNMENT 2.2
## Submitted by: FARHAN ASIF (A23052200097)

Q1)

In [14]:
import pandas as pd
import numpy as np

In [15]:
#Creating a Dictionary of series
d = {
    'Name': pd.Series(['Tom', 'James', 'Ricky', 'Vin', 'Steve', 'Smith', 'Jack']),
    'Age': pd.Series([25, 26, 25, 23, 30, 29, 23]),
    'Rating': pd.Series([4.23, 3.24, 3.98, 2.56, 3.20, 4.6, 3.8])
}

In [16]:
print(d["Name"].shape, d["Age"].shape, d["Rating"].shape)

(7,) (7,) (7,)


In [17]:
print(d["Name"].size, d["Age"].size, d["Rating"].size)

7 7 7


In [18]:
print(d["Name"].dtype, d["Age"].dtype, d["Rating"].dtype)

object int64 float64


In [19]:
print(d["Name"].head(), d["Age"].head(), d["Rating"].head())

0      Tom
1    James
2    Ricky
3      Vin
4    Steve
dtype: object 0    25
1    26
2    25
3    23
4    30
dtype: int64 0    4.23
1    3.24
2    3.98
3    2.56
4    3.20
dtype: float64


In [20]:
print(d["Name"].tail(), d["Age"].tail(), d["Rating"].tail())

2    Ricky
3      Vin
4    Steve
5    Smith
6     Jack
dtype: object 2    25
3    23
4    30
5    29
6    23
dtype: int64 2    3.98
3    2.56
4    3.20
5    4.60
6    3.80
dtype: float64


In [21]:
ipl_data = 
{
    'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings', 'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'], 
    'Rank': [1, 2, 2, 3, 3, 4, 1, 1, 2, 4, 1, 2], 
    'Year': [2014, 2015, 2014, 2015, 2014, 2015, 2016, 2017, 2016, 2014, 2015, 2017], 
    'Points': [876, 789, 863, 673, 741, 812, 756, 788, 694, 701, 804, 690]
} 

SyntaxError: invalid syntax (<ipython-input-21-5f193eb6340f>, line 1)

In [22]:
df = pd.DataFrame(ipl_data)

In [23]:
 print(df)

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690


In [24]:
#Group by Team
print(df.groupby("Team").first())

        Rank  Year  Points
Team                      
Devils     2  2014     863
Kings      3  2014     741
Riders     1  2014     876
Royals     4  2014     701
kings      4  2015     812


In [25]:
#Group by Rank
print(df.groupby("Rank").first())

        Team  Year  Points
Rank                      
1     Riders  2014     876
2     Riders  2015     789
3     Devils  2015     673
4      kings  2015     812


In [26]:
#Group by Year
print(df.groupby("Year").first())

        Team  Rank  Points
Year                      
2014  Riders     1     876
2015  Riders     2     789
2016   Kings     1     756
2017   Kings     1     788


In [27]:
# Group by (Team,Rank and Year)
print(df.groupby(['Team','Rank','Year']).first())

                  Points
Team   Rank Year        
Devils 2    2014     863
       3    2015     673
Kings  1    2016     756
            2017     788
       3    2014     741
Riders 1    2014     876
       2    2015     789
            2016     694
            2017     690
Royals 1    2015     804
       4    2014     701
kings  4    2015     812


Q2)

In [28]:
import numpy

In [29]:
a = np.array([10, 20, 30]) 
b = np.array([3, 5, 7])

In [30]:
#Applying power function
print(np.power(a,b))

[     1000   3200000 395163520]


In [31]:
#Applying mod function
print(np.mod(a,b))

[1 0 2]


In [32]:
#Applying remainder function
print(np.remainder(a,b))

[1 0 2]
